name: Build and deploy doc

on: workflow_dispatch

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docs
        run: yarn run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: api-docs
          path: docs/.vuepress/dist/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: api-docs

      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
